### ISSUE TITLE
TC provider does not return old builds

### ISSUE THREAD

**Issue by gedgei** [BalticAmadeus/BuildWatch#1]
There's a bug in TC provider, where it only returns builds that it finds in the latest builds XML (URI: /httpAuth/app/rest/builds). If some build was completed a longer time ago, it will not be included in the latest builds XML, therefore, it will not be displayed in the UI. Need to fix that.

**Comment by tomasmaconko** [comment]
I think this is already fixed as there is a middle tier, which aggregates builds and provides the status of those. So even if TC provider does not return the list of all builds, BuildServer will return them from his own data source.

**Comment by akompanas** [comment]
The presense of database softens the issue in common situations but it does not solve the core issue that the data source provides incomplete information.
